# 模型服务配置
model_service:
  base_url: "http://localhost:8080"  # 队友模型服务地址
  api_endpoints:
    get_data: "/api/model/data"      # 获取数据接口
    health_check: "/api/health"      # 健康检查接口
  timeout: 30
  retry_times: 3
  retry_delay: 2

# 阿里云配置
alibaba_cloud:
  # API网关或ECS服务器地址
  server_url: "https://your-domain.com"  # 替换为你的域名
  api_endpoints:
    upload_data: "/api/v1/data/upload"
    health_check: "/api/health"
    stats: "/api/v1/stats"
  # 如果使用OSS直传
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    bucket_name: "your-bucket-name"
    access_key_id: "${ALIYUN_ACCESS_KEY_ID}"
    access_key_secret: "${ALIYUN_ACCESS_KEY_SECRET}"
  timeout: 60
  retry_times: 5
  retry_delay: 3

# 调度配置
scheduler:
  # 数据获取频率 (秒)
  fetch_interval: 60
  # 是否启动时立即执行一次
  run_immediately: true
  # 最大并发任务数
  max_workers: 3

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  rotation: "100 MB"
  retention: "7 days"

# 数据处理配置
data_processing:
  # 数据验证规则
  validation:
    max_size_mb: 50
    required_fields: ["timestamp", "data"]
  # 数据转换
  transformation:
    add_metadata: true
    compress: false
